version: '3'



services:
  mysql:
    image: mysql:8.0.36
    container_name: bibi
    volumes:
      - ./pkg/conf/sql:/docker-entrypoint-initdb.d
      - ./pkg/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bibi_db
      - MYSQL_ROOT_PASSWORD=114514
      - TZ=Asia/Shanghai
    security_opt:
      - seccomp:unconfined
    restart: always
    network_mode: bridge

  redis:
    image: redis:6.0.16
    container_name: redis
    ports:
      - "6379:6379"
#    volumes:
#      - ./pkg/data/redis:/data
    restart: always
    network_mode: bridge
