// Code generated by hertz generator.

package main

import (
	"bibi/biz/dal/cache"
	"bibi/biz/dal/db"
	"bibi/biz/mw/jwt"
	"bibi/pkg/conf"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/logger/accesslog"
)

// @title           BibiBibi
// @version         1.0
// @description     video website

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8000
// @BasePath  /bibi
func main() {

	db.Init(conf.Init()) //非常丑的方式避免了循环引用，但真的很丑...
	jwt.Init()
	cache.Init()

	h := server.New(
		server.WithHostPorts(conf.ServerAddr),
		server.WithStreamBody(true),
		server.WithMaxRequestBodySize(16*1024*1024), //最大字节数
	)

	h.Use(accesslog.New()) //todo:log
	register(h)

	h.Spin()
}
