// Code generated by hertz generator.

package main

import (
	"bibi/biz/mw/jwt"
	"bibi/pkg/conf"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/logger/accesslog"
)

// @title           BibiBibi
// @version         1.0
// @description     video website

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8000
// @BasePath  /bibi
func main() {

	conf.Init()
	jwt.Init()

	h := server.New(server.WithHostPorts(":8000"))
	h.Use(accesslog.New()) //todo:log
	register(h)

	h.Spin()
}
