// Code generated by hertz generator.

package chat

import (
	"bibi/biz/service/chat_service"
	"bibi/pkg/errno"
	"bibi/pkg/pack"
	"context"
	"github.com/hertz-contrib/websocket"
	"log"

	chat "bibi/biz/model/chat"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Chat .
// @Summary chat(websocket)
// @Description chat online
// @Accept json/form
// @Produce json
// @Param target_id query int true "目标id"
// @Param Authorization header string true "token"
// @router /bibi/message/ws [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.MessageChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(chat.MessageChatResp)

	v, _ := c.Get("current_user_id")
	id := v.(int64)

	if id == req.TargetID {
		resp.Base = pack.BuildChatBaseResp(errno.ParamError)
		c.JSON(consts.StatusOK, resp)
		return
	}

	var upGrader = websocket.HertzUpgrader{
		ReadBufferSize:  1024,
		WriteBufferSize: 1024,
		CheckOrigin: func(c *app.RequestContext) bool {
			return true
		},
	}
	//hertz wcnm
	//HertzHandler receives a websocket connection after the handshake has been completed.
	//在匿名函数里面开启send和recv
	client := new(chat_service.Client)

	err = upGrader.Upgrade(c, func(conn *websocket.Conn) {
		client = &chat_service.Client{
			ID:       id,
			TargetId: req.TargetID,
			Socket:   conn,
			Send:     make(chan []byte),
		}
		//将用户注册到用户管理上
		chat_service.Manager.Register <- client
		go client.Read()
		go client.Write()
		for {
		} //直到conn被关闭才会退出
	})
	if err != nil {
		log.Print("upgrade:", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
}

// MessageAction .
// @Summary message_action
// @Description send message to user or group
// @Accept json/form
// @Produce json
// @Param target_id query int true "目标id"
// @Param content query string true "信息"
// @Param action_type query int true "暂时只有单聊所以填啥都行"
// @Param Authorization header string true "token"
// @router /bibi/message/action [GET]
func MessageAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.MessageActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(chat.MessageActionResp)

	v, _ := c.Get("current_user_id")
	id := v.(int64)

	err = chat_service.NewMessageService(ctx).SendMessage(&req, id)

	resp.Base = pack.BuildChatBaseResp(err)
	c.JSON(consts.StatusOK, resp)
}
