mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 114514
  dbname: bibi_db
redis:
  addr: 127.0.0.1:6379
service:
  mode: debug
  port: :8888
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accesskeyid: LTAI5tLxvgGfKqWqUc7t9mLe
  accesskeysecret: 4h6MoIFctgbciZW19qwnup7IYUqxwz
  bucketname: bibi-demo
  main-directory: bibi
page:
  page-size: 15