// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bibi/follow/action": {
            "post": {
                "description": "follow action",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "follow_action",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "操作对象id",
                        "name": "object_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0：取消关注;1：关注",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/follow/follower": {
            "get": {
                "description": "list your followers",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "follower_list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/follow/following": {
            "get": {
                "description": "list your followed",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "following_list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/follow/friend": {
            "get": {
                "description": "list your friends",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "friend_list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/interaction/comment/create": {
            "post": {
                "description": "comment video",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "comment_create",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "正文",
                        "name": "content",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/interaction/comment/delete": {
            "post": {
                "description": "delete your comment",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "comment_delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "评论id",
                        "name": "comment_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/interaction/comment/list": {
            "post": {
                "description": "show video's comments",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "comment_list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/interaction/like/action": {
            "post": {
                "description": "like or dislike video",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "like_action",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "点赞:0;取消点赞:1",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/interaction/like/list": {
            "get": {
                "description": "show the list of your liked videos",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "like_list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/message/record": {
            "get": {
                "description": "get message record",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "message_record",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目标id",
                        "name": "target_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "2024-02-29",
                        "name": "from_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "2024-03-01",
                        "name": "to_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/message/ws": {
            "get": {
                "description": "chat online",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "chat(websocket)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目标id",
                        "name": "target_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/user": {
            "get": {
                "description": "show user's info",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/user/avatar/upload": {
            "put": {
                "description": "revise user's avatar",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "PUTAvatar",
                "parameters": [
                    {
                        "type": "file",
                        "description": "头像",
                        "name": "avatar_file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/user/login": {
            "post": {
                "description": "userLogin",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/user/register": {
            "post": {
                "description": "userRegister",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/user/switch2fa": {
            "get": {
                "description": "switch on/off 2fa mode",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "switch_2fa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "关闭:0;开启:1",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "otp",
                        "name": "otp",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/video/hot": {
            "get": {
                "description": "hot video rank",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "HotVideo",
                "responses": {}
            }
        },
        "/bibi/video/published": {
            "post": {
                "description": "list user's videos",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ListVideo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/video/search": {
            "post": {
                "description": "search videos",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "SearchVideo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索内容",
                        "name": "param",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bibi/video/upload": {
            "post": {
                "description": "put video",
                "consumes": [
                    "json/form"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "PutVideo",
                "parameters": [
                    {
                        "type": "file",
                        "description": "视频文件",
                        "name": "video_file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "视频封面",
                        "name": "cover",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/bibi",
	Schemes:          []string{},
	Title:            "BibiBibi",
	Description:      "video website",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
