basePath: /bibi
host: localhost:8000
info:
  contact: {}
  description: video website
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: BibiBibi
  version: "1.0"
paths:
  /bibi/follow/action:
    post:
      consumes:
      - json/form
      description: follow action
      parameters:
      - description: 操作对象id
        in: query
        name: object_uid
        required: true
        type: integer
      - description: 0：取消关注;1：关注
        in: query
        name: action_type
        required: true
        type: integer
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: follow_action
  /bibi/follow/follower:
    get:
      consumes:
      - json/form
      description: list your followers
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: follower_list
  /bibi/follow/following:
    get:
      consumes:
      - json/form
      description: list your followed
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: following_list
  /bibi/follow/friend:
    get:
      consumes:
      - json/form
      description: list your friends
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: friend_list
  /bibi/interaction/comment/create:
    post:
      consumes:
      - json/form
      description: comment video
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 正文
        in: query
        name: content
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: comment_create
  /bibi/interaction/comment/delete:
    post:
      consumes:
      - json/form
      description: delete your comment
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 评论id
        in: query
        name: comment_id
        required: true
        type: integer
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: comment_delete
  /bibi/interaction/comment/list:
    post:
      consumes:
      - json/form
      description: show video's comments
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 页码
        in: query
        name: page_num
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: comment_list
  /bibi/interaction/like/action:
    post:
      consumes:
      - json/form
      description: like or dislike video
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 点赞:0;取消点赞:1
        in: query
        name: action_type
        required: true
        type: integer
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: like_action
  /bibi/interaction/like/list:
    get:
      consumes:
      - json/form
      description: show the list of your liked videos
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: like_list
  /bibi/user:
    get:
      consumes:
      - json/form
      description: show user's info
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Information
  /bibi/user/avatar/upload:
    put:
      consumes:
      - json/form
      description: revise user's avatar
      parameters:
      - description: 头像
        in: formData
        name: avatar_file
        required: true
        type: file
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: PUTAvatar
  /bibi/user/login:
    post:
      consumes:
      - json/form
      description: userLogin
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Login
  /bibi/user/register:
    post:
      consumes:
      - json/form
      description: userRegister
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Register
  /bibi/video/hot:
    get:
      consumes:
      - json/form
      description: hot video rank
      produces:
      - application/json
      responses: {}
      summary: HotVideo
  /bibi/video/published:
    post:
      consumes:
      - json/form
      description: list user's videos
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: ListVideo
  /bibi/video/search:
    post:
      consumes:
      - json/form
      description: search videos
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 搜索内容
        in: query
        name: param
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: SearchVideo
  /bibi/video/upload:
    post:
      consumes:
      - json/form
      description: put video
      parameters:
      - description: 视频文件
        in: formData
        name: video_file
        required: true
        type: file
      - description: 标题
        in: query
        name: title
        required: true
        type: string
      - description: 视频封面
        in: formData
        name: cover
        required: true
        type: file
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: PutVideo
swagger: "2.0"
